{{- if .Values.is_production }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: homelabping-autoscaler
spec:
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: homelabping-rollout
{{- end }}
